export const LOGO_IMG = 'assets/Nanova-Env-logo.png';
export const LOGO_FOOT = 'assets/Nei-footer-logo.png';
export const TEL = '+1(573)476-6335';
export const FACEBOOK_IMG = 'assets/Facebook.png';
export const LINKEDIN_IMG = 'assets/Linkedin.png';
export const TWITTER_IMG = 'assets/Twitter.png';
export const YOUTUBE_IMG = 'assets/YouTube.png';
export const COPY_RIGHT = 'Copyright © 2021 Nanova Environmental, Inc. All Rights Reserved.'
export const MAIN_BG_IMG = 'assets/mainpage-background.png';
export const COMPACKT_GC = 'assets/Compact-GC.png';
export const ONLINE_MONITORING = 'assets/Online-Monitoring.png';
export const SENSORS = 'assets/Sensors.png';
export const SUPPORT_BG = 'assets/support-bg.png';
export const ABOUT_US_BG = 'assets/Aboutus.png';
export const BUSI_PART_BG ='assets/Business-Partners.png';
export const JOIN_US_BG = 'assets/Career.png';
export const DUVAS_IMG = 'assets/Duvas-Logo.png';
export const SATIR_IMG = 'assets/Satir-Logo.png';
export const SCENTR_IMG = 'assets/Scentroid-logo.png';